//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateStuff
    {
        public int IDCertificate { get; set; }
        public System.DateTime Date { get; set; }
        public int IDStuff { get; set; }
        public int IDRouting { get; set; }
    
        public virtual Routing Routing { get; set; }
        public virtual Stuff Stuff { get; set; }
    }
}
