//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumables
    {
        public int IDСonsumables { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public int Unit { get; set; }
    
        public virtual Units Units { get; set; }
    }
}
