//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DispatcherEntities : DbContext
    {
        public DispatcherEntities()
            : base("name=DispatcherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batch { get; set; }
        public virtual DbSet<CertificateEquipment> CertificateEquipment { get; set; }
        public virtual DbSet<CertificateStuff> CertificateStuff { get; set; }
        public virtual DbSet<CertificationPeriod> CertificationPeriod { get; set; }
        public virtual DbSet<Consumables> Consumables { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<EquipmentStatus> EquipmentStatus { get; set; }
        public virtual DbSet<MSL> MSL { get; set; }
        public virtual DbSet<OperationHistory> OperationHistory { get; set; }
        public virtual DbSet<OperationMSL> OperationMSL { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostBinding> PostBinding { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Routing> Routing { get; set; }
        public virtual DbSet<StaffStatus> StaffStatus { get; set; }
        public virtual DbSet<Stuff> Stuff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Units> Units { get; set; }
    }
}
