//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationMSL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationMSL()
        {
            this.OperationHistory = new HashSet<OperationHistory>();
        }
    
        public int IDOperation { get; set; }
        public Nullable<int> IDMSL { get; set; }
        public byte[] AVM { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> Routing { get; set; }
        public Nullable<System.TimeSpan> InteractionTime { get; set; }
        public string TypeOfProcessing { get; set; }
        public string Note { get; set; }
    
        public virtual MSL MSL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationHistory> OperationHistory { get; set; }
        public virtual Routing Routing1 { get; set; }
    }
}
