//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationHistory
    {
        public int IDRecord { get; set; }
        public int IDBatch { get; set; }
        public int IDOperation { get; set; }
        public int IDStaff { get; set; }
        public int IDEquipment { get; set; }
        public string Note { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual OperationMSL OperationMSL { get; set; }
        public virtual Stuff Stuff { get; set; }
    }
}
