//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispatcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stuff()
        {
            this.CertificateStuff = new HashSet<CertificateStuff>();
            this.OperationHistory = new HashSet<OperationHistory>();
        }
    
        public int IDStuff { get; set; }
        public int IDDistrict { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int FirstPostBind { get; set; }
        public Nullable<int> SecondPostBind { get; set; }
        public int PersonnelNumber { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Education { get; set; }
        public string ResidenceAddress { get; set; }
        public Nullable<int> WorkPhoneNumber { get; set; }
        public Nullable<int> PersonalPhoneNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateStuff> CertificateStuff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationHistory> OperationHistory { get; set; }
        public virtual PostBinding PostBinding { get; set; }
        public virtual StaffStatus StaffStatus { get; set; }
    }
}
